# Generated by Django 4.2 on 2023-06-03 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('kerala', 'kerala'), ('tamil nadu', 'tamil nadu'), ('karnataka', 'karnaraka')], max_length=100),
        ),
    ]
